### ISSUE TITLE
[F-REQ] !!

### ISSUE THREAD

**Issue by simploita78** [Alujjdnd/Ngrok-LAN#48]
i have a Minecraft premium account but some of my friends doesnt i just want to ask that if this modpack work with my friend's cracked account (Tlauncher) if yes, thank you and sorry for inconvenience, if not then Can you please make it work. simply because whats the point of playing Alone.

I hope you understand
i appreciate your work

**Comment by Flooflez** [comment]
Hi, this mod is effectively deprecated and will not be updated. 
This mod did support cracked accounts for more recent versions of Minecraft, but due to Ngrok updates it is highly recommended you use another mod ([see deprecation notice](https://github.com/Alujjdnd/Ngrok-LAN/blob/1.20/IMPORTANT.md))

I am unaware if these other mods support cracked accounts.
